[tools]
rojo = { source = "rojo-rbx/rojo", version = "7.4.0" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.11.3" }
selene = {source = "kampfkarren/selene", version = "0.25.0"}
luau-lsp = {source="JohnnyMorganz/luau-lsp", version="1.20.2"}
wally = { source = "UpliftGames/wally", version = "0.3.1"}
wally-package-types = {source = "JohnnyMorganz/wally-package-types", version = "1.2.0"}